# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Portfolio do Lucas
email: "lucasgruenerlima@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  A Bootstrap 4 start up project for Jekyll and Github Pages
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "lucasgruener/lucasgruener.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-include-cache
# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
